import type { Service, PricingTier } from '@/types'

export const services: Service[] = [
  // Database & Infrastructure
  {
    id: 'db-support',
    icon: 'HeadsetIcon',
    titleKey: 'services.dbSupport.title',
    descriptionKey: 'services.dbSupport.description',
    path: '/services/db-support',
    category: 'database',
  },
  {
    id: 'postgresql',
    icon: 'DatabaseIcon',
    titleKey: 'services.postgresql.title',
    descriptionKey: 'services.postgresql.description',
    path: '/services/postgresql',
    category: 'database',
  },
  {
    id: 'dwh-data-lakes',
    icon: 'WarehouseIcon',
    titleKey: 'services.dwh.title',
    descriptionKey: 'services.dwh.description',
    path: '/services/dwh-data-lakes',
    category: 'database',
  },
  {
    id: 'nosql',
    icon: 'LayersIcon',
    titleKey: 'services.nosql.title',
    descriptionKey: 'services.nosql.description',
    path: '/services/nosql',
    category: 'database',
  },
  {
    id: 'db-migration',
    icon: 'ArrowRightLeftIcon',
    titleKey: 'services.migration.title',
    descriptionKey: 'services.migration.description',
    path: '/services/db-migration',
    category: 'database',
  },
  {
    id: 'dba-training',
    icon: 'GraduationCapIcon',
    titleKey: 'services.training.title',
    descriptionKey: 'services.training.description',
    path: '/services/dba-training',
    category: 'database',
  },
  {
    id: 'db-security',
    icon: 'ShieldCheckIcon',
    titleKey: 'services.security.title',
    descriptionKey: 'services.security.description',
    path: '/services/db-security',
    category: 'database',
  },
  {
    id: 'ai-ml',
    icon: 'BrainCircuitIcon',
    titleKey: 'services.aiml.title',
    descriptionKey: 'services.aiml.description',
    path: '/services/ai-ml',
    category: 'database',
  },
  // Data Platform (IOMETE)
  {
    id: 'data-platform',
    icon: 'CloudIcon',
    titleKey: 'services.platform.title',
    descriptionKey: 'services.platform.description',
    path: '/services/data-platform',
    category: 'platform',
  },
  {
    id: 'etl-pipeline',
    icon: 'WorkflowIcon',
    titleKey: 'services.etl.title',
    descriptionKey: 'services.etl.description',
    path: '/services/etl-pipeline',
    category: 'platform',
  },
  {
    id: 'bi-analytics',
    icon: 'BarChart3Icon',
    titleKey: 'services.bi.title',
    descriptionKey: 'services.bi.description',
    path: '/services/bi-analytics',
    category: 'platform',
  },
  {
    id: 'db-governance',
    icon: 'ScaleIcon',
    titleKey: 'services.governance.title',
    descriptionKey: 'services.governance.description',
    path: '/services/db-governance',
    category: 'platform',
  },
]

export const pricingTiers: PricingTier[] = [
  {
    id: 'free',
    nameKey: 'prices.free.name',
    price: '$0',
    featuresKeys: [
      'prices.free.feature1',
      'prices.free.feature2',
      'prices.free.feature3',
      'prices.free.feature4',
    ],
    ctaKey: 'prices.free.cta',
  },
  {
    id: 'enterprise',
    nameKey: 'prices.enterprise.name',
    price: '$500',
    minKey: 'prices.enterprise.min',
    featuresKeys: [
      'prices.enterprise.feature1',
      'prices.enterprise.feature2',
      'prices.enterprise.feature3',
      'prices.enterprise.feature4',
      'prices.enterprise.feature5',
    ],
    highlighted: true,
    ctaKey: 'prices.enterprise.cta',
  },
  {
    id: 'business',
    nameKey: 'prices.business.name',
    price: 'Custom',
    minKey: 'prices.business.min',
    featuresKeys: [
      'prices.business.feature1',
      'prices.business.feature2',
      'prices.business.feature3',
      'prices.business.feature4',
      'prices.business.feature5',
    ],
    ctaKey: 'prices.business.cta',
  },
]
